#-----------Général-----------#

#Redirection sur la page home
/:
  controller: Home
  action: default

#Affichge de la page Home
/home:
  controller: Home
  action: default

#Affichage de la page pour se connecter
/se-connecter:
  controller: User
  action: login

#Affichage de la page pour se déconnecter
/se-deconnecter:
  controller: User
  action: logout

#Affichage de la page pour s'inscrire
/s-inscrire:
  controller: User
  action: register

/confirmation:
  controller: User
  action: registerConfirm

/se-connecter/verifications:
  controller: User
  action: logCheck

#Affichage de la page en cas d'erreur 404
/vous-etes-perdu:
  controller: Errors
  action: quatreCentQuatre

#Affichage de la page de profil
/profile:
  controller: User
  action: index 


#Modifier son profil
/profile/update:
  controller: User
  action: update

/mot-de-passe-oublie:
  controller: User
  action: forgotPassword

/nouveau-mot-de-passe:
  controller: User
  action: newPassword

/suppression-de-compte:
  controller: User
  action: delete

#Affichage des conditions d'utilisations
/conditions:
  controller: Home
  action: conditions


#-----------Connexion client HF / Dashboard Client-----------#

#Affichage de l'accueil du backoffice client
/settings:
  controller: User
  action: default
  role: 2;3

#Affichage de la gestion des page clientes
/settings/mes-pages:
  controller: Page
  action: default

#Affichage de la gestion des page clientes
/settings/comment/list:
  controller: Comment
  action: list
  role: 2;3


#Affichage de la gestion des informations de l'hotel
/settings/update_hotel:
  controller: Hotel
  action: editForm

/settings/hotel/edit:
  controller: Hotel
  action: edit


#Affichage de la modification du contenu des page clientes
/settings/page/formpage:
  controller: Page
  action: formpage

  #Validation des changements de la page
/settings/page/update:
  controller: Page
  action: update


  #Affichage formulaire creation de page 
/settings/page/formCreate:
  controller: Page
  action: formCreatePage


  #Affichage formulaire creation de page 
/settings/page/create:
  controller: Page
  action: create
  
/settings/page/status:
  controller: Page
  action: status


#Affichage de la page pour gérer l'apparence des page clientes
/settings/apparences:
  controller: Style
  action: list

#Affichage de la page paramètre du client
/settings/parametres:
  controller: Comment
  action: formComment

#Créer commentaire
/settings/create:
  controller: Comment
  action: create

#Affichage de la FAQ
/settings/faq:
  controller: Question
  action: list

#Poser une question
/settings/faq/create:
  controller: Question
  action: create
  role: 2

/settings/room/list:
  controller: Room
  action: list

/settings/room/edit:
  controller: Room
  action: edit

/settings/room/status:
  controller: Room
  action: status

/settings/room/create:
  controller: Room
  action: create

/settings/room/form:
  controller: Room
  action: formRoom

/settings/room/editForm:
  controller: Room
  action: editForm

/settings/room/delete:
  controller: Room
  action: delete

/settings/service/create:
  controller: Service
  action: create

/settings/service/form:
  controller: Service
  action: formService

/settings/service/list:
  controller: Service
  action: list

/settings/service/edit:
  controller: Service
  action: edit

/settings/service/editForm:
  controller: Service
  action: editForm

/settings/service/delete:
  controller: Service
  action: delete

  
/settings/service/status:
  controller: Service
  action: status

#---Actions---#

#Créer un commentaire
/settings/parametres/add_comment:
  controller: Comment
  action: comment
  

#Signal
/settings/comment_active:
  controller: Comment
  action: update


#Ajouter une question
/settings/faq/add_question:
  controller: Question
  action: create

/settings/create_hotel:
  controller: Hotel
  action: createHotel
 

/add_hotel:
  controller: Hotel
  action: create
  role: 2

/settings/permissions:
  controller: User
  action: list

/settings/user/moderator:
  controller: User
  action: formRegisterModerator
  
/settings/user/add_moderator:
  controller: User
  action: create

#Changer le role d'un user
/settings/perm_modify:
  controller: User
  action: update  

/settings/hotel/delete:
  controller: Hotel
  action: delete
  role: 2  


#-----------Connexion admin HF / Dashboard Admin-----------#

#Affichage de la vue
/dashboard:
  controller: User
  action: default
  role: 1

#Backoffice gestion des page HF
/dashboard/mes-pages:
  controller: Page
  action: default

#Affichage de la modification du contenu des page clientes
/dashboard/page/formpage:
  controller: Page
  action: formpage

#Validation des changements de la page
/dashboard/page/update:
  controller: Page
  action: update

#Backoffice gestion de l'apprence du site HF
/dashboard/apparences:
  controller: Style
  action: list

#Backoffice gestion des paramètres HF
/dashboard/parametres:
  controller: Setting
  action: list

#Backoffice gestion de la FAQ
/dashboard/faq:
  controller: Question
  action: list

#Afficher ou cacher une question
/dashboard/faq/update:
  controller: Question
  action: update

#Backoffice gestion des réponses aux FAQ
/dashboard/faq/anwser:
  controller: Answer
  action: default

#Action de création de la réponse à une question
/dashboard/faq/answer/create:
  controller: Answer
  action: create

#Affichage questions pour répondre
/dashboard/faq/answer/show:
  controller: Answer
  action: show

/dashboard/user/moderator:
  controller: User
  action: formRegisterModerator
  
/dashboard/user/add_moderator:
  controller: User
  action: create

#---Actions---#

#Lister les commentaires des utilisateurs
/dashboard/comments:
  controller: Comment
  action: list


#Lister les commentaires signalés des clients
/dashboard/comment/signal:
  controller: Comment
  action: signal

/dashboard/comment/valid:
  controller: Comment
  action: verified


#Afficher les commentaires sur l'accueil
/dashboard/comment_active:
  controller: Comment
  action: update
  role: 3

#Afficher les commentaires sur l'accueil
/dashboard/comment/delete:
  controller: Comment
  action: destroy



  
#Lister les utilisateurs et leurs roles
/dashboard/permissions:
  controller: User
  action: list

#Changer le role d'un user
/dashboard/perm_modify:
  controller: User
  action: update


#Lister les hotels et leurs status
/dashboard/hotels:
  controller: Hotel
  action: list


#Affichage des détails de l'hotel
/dashboard/details_hotel:
  controller: Hotel
  action: show


#Valider hotel
/dashboard/update:
  controller: Hotel
  action: update

