#-----------Général-----------#
/:
  controller: Home
  action: default

/home:
  controller: Home
  action: default

/se-connecter:
  controller: User
  action: login

/se-deconnecter:
  controller: User
  action: logout

/s-inscrire:
  controller: User
  action: register

/confirmation:
  controller: User
  action: registerConfirm

/se-connecter/verifications:
  controller: User
  action: logCheck

/vous-etes-perdu:
  controller: Errors
  action: quatreCentQuatre

/profile:
    controller: User
    action: index

/profile/modify: #Modifier son profil
  controller: User
  action: update

#-----------Connexion client HF / Dashboard Client-----------#

#Affichage de la vue
/settings:
  controller: DashboardUser
  action: default

/settings/mes-pages:
  controller: DashboardUser
  action: userPages

/settings/apparences:
  controller: DashboardUser
  action: userDesign

/settings/parametres:
  controller: DashboardUser
  action: userSettings

/settings/faq:
  controller: DashboardUser
  action: userFaq


#Actions
/settings/parametres/add_comment: #Créer un commentaire
  controller: Comment
  action: comment

/settings/faq/add_question: #Ajouter une question
  controller: Question
  action: create

#-----------Connexion admin HF / Dashboard Admin-----------#

#Affichage de la vue
/dashboard:
  controller: DashboardAdmin
  action: default

/dashboard/mes-pages:
  controller: DashboardAdmin
  action: adminPages

/dashboard/apparences:
  controller: DashboardAdmin
  action: adminDesign

/dashboard/parametres:
  controller: DashboardAdmin
  action: adminSettings

/dashboard/faq:
  controller: DashboardAdmin
  action: adminFaq

/dashboard/faq/anwser:
  controller: Answer
  action: default

/dashboard/faq/answer/create:
  controller: Answer
  action: create

#Actions
/dashboard/comments: #Lister les commentaires des utilisateurs
  controller: Comment
  action: list

/dashboard/comment_active: #Afficher les commentaires sur l'accueil
  controller: Comment
  action: update

/dashboard/permissions: #Lister les utilisateurs et leurs roles
  controller: User
  action: list

/dashboard/perm_modify: #Changer le role d'un user
  controller: User
  action: update

/dashboard/faq/reply: #Répondre à un commentaire
  controller: Answer
  action: create